name: linux
on: [push, pull_request]
jobs:

  build:
    name: build
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Install mbedTLS
      run: sudo apt-get install libmbedtls-dev

    - name: Install ninja
      run: sudo apt-get install ninja-build

    - name: Configure
      run: mkdir build && cd build && cmake -G Ninja -DNNG_ENABLE_TLS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..

    - name: Build
      run: cd build && ninja

    - uses: actions/upload-artifact@v3
      with:
        name: nng-linux
        path: build/libnng.a