name: windows
on: [push, pull_request]
jobs:

  build:
    name: build
    runs-on: [ windows-latest ]
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build --config=Release -DBUILD_SHARED_LIBS=ON

    - uses: actions/upload-artifact@v3
      with:
        name: nng-win
        path: build/Release/nng.lib

